#!/bin/bash

docker-compose up -d --force-recreate
# for better resample uncomment the following line and create /etc/asound.conf with a config line: defaults.pcm.rate_converter "speexrate_best"
#docker exec -i tidal_connect bash -c "echo 'deb http://legacy.raspbian.org/raspbian/ stretch main contrib non-free rpi firmware' > /etc/apt/sources.list && apt update && apt install libasound2-plugins libspeexdsp1 -y"
docker-compose logs -f
