#!/bin/bash

# start/stop script for running the Speaker Controller Application
# This application enables controlling Tidal from the mobile device (Volume,Start/Stop,Next/Prev etc)

function start() {
  # Stop if already running
  if pgrep -f ^/app/ifi-tidal-release/bin/speaker_controller_application >/dev/null 2>&1
  then
    echo "Already running..."
    stop
  fi

  echo "Starting Speaker Controller Application..."
  docker exec -ti tidal_connect /usr/bin/tmux new-session -d -s speaker_controller_application '/app/ifi-tidal-release/bin/speaker_controller_application'
}


function stop() {
  echo "Stopping Speaker Controller Application..."
  docker exec -ti tidal_connect /usr/bin/tmux kill-session -t speaker_controller_application
}


case "$1" in 
    start)   start ;;
    stop)    stop ;;
    restart) stop; start ;;
    *) echo "usage: $0 start|stop|restart" >&2
       echo ""
       exit 1
       ;;
esac

